version: "3.4"

services:
  webapp:
    container_name: celsure
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.dev
    ports:
      - 48000:8000
    depends_on:
      - "postgres"
  postgres:
    image: postgres

  redis:
    image: redis:6-alpine
