# Generated by Django 3.2.16 on 2022-12-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0002_alter_policy_phone_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="quote",
            field=models.JSONField(null=True),
        ),
    ]
