# Generated by Django 3.2.16 on 2022-12-21 10:39

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0003_policy_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="policy",
            name="status",
            field=django_fsm.FSMField(default="pending", max_length=50),
        ),
        migrations.DeleteModel(
            name="PolicyActivity",
        ),
    ]
