name: Run tests

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          cp .env.sample .env.ci
          echo 'WEB3_PROVIDER_URI=${{ secrets.ALCHEMY_URL }}' >> .env.ci
          docker-compose -f docker-compose.test-image.yml build
          docker-compose -f docker-compose.test-image.yml up \
              --exit-code-from webapp \
              --abort-on-container-exit \
              --force-recreate
